### ISSUE TITLE
(Decode, claimset) Cannot read properties of undefined

### ISSUE THREAD

**Issue by alessandro-verdura-maersk** [arbs-io/vscode-jwt-decoder#21]
Hello, thanks for this really nice extension!

Unfortunately I'm getting this error when trying to either decode or show the JWT claimset:

```
Command 'jwt: JWT: Show token in decoded json view' resulted in an error (Cannot read properties of undefined (reading 'toString'))
```

As a result only the hover functionality works for me.

I tried with highlighting the JWT string, with saving the token in a file, but nothing seems to work.

Could you help out? Thanks!

macOS Ventura 13.2.1
VSCode v1.75.1
vscode-jwt-decoder v1.0.13

**Comment by arbs-io** [comment]
Hi @alessandro-verdura-maersk 
Many thanks for raising this issue. 
Is there any way you could share a sample token or give me some more info IDP token type. Will get it fixed asap but need the info to validate the scenario

**Comment by arbs-io** [comment]
Hi @alessandro-verdura-maersk 
Could you try with one of the samples and let me know if any of them are similar to your token(s) which aren't working 
[Sample Tokens](https://github.com/arbs-io/vscode-jwt-decoder/tree/main/sample)

**Comment by alessandro-verdura-maersk** [comment]
hi @arbs-io , thanks for the quick reply! I tried with the all of those tokens and none of them worked unfortunately. The token I was trying the extension with when reporting the issue is a standard [Microsoft identity platform access tokens](https://learn.microsoft.com/en-us/azure/active-directory/develop/access-tokens)

**Comment by arbs-io** [comment]
Going to close as I can replicate this issue. Seems fine on all platforms for me
